### ISSUE TITLE
Please upload to the VSCode extension marketplace.

### ISSUE THREAD

**Issue by singlewindy** [NilsJPWerner/autoDocstring#1]
Great work. I believe this is a very useful extension to VSCode. It works great in my machine. 

Can you upload it to VSCode extension marketplace? so that more people can find and use it.

**Comment by NilsJPWerner** [comment]
@singlewindy Thanks! I put this project on the backburner for a while, but since you found it and like it I will finish it and publish it to the marketplace when I get some free time :)

**Comment by NilsJPWerner** [comment]
Published
