### ISSUE TITLE
Custom Docstring Template Python

### ISSUE THREAD

**Issue by DontKnowMy** [NilsJPWerner/autoDocstring#100]
I would like to adjust my .mustache file in a way that different docstring are created in dependance of where I want to create the docstring (class, function, beginning of file et cetera).

Does anyone know how to do that?

**Comment by NilsJPWerner** [comment]
autoDocstring currently only supports function docstrings. There are separate issues about supporting more than that. I can revisist this once that functionality is added.

**Comment by a-wilsonchen** [comment]
Hi is this function implemented? 
If yes, can you please share how to set up multiple template for different scenario?(class function etc.)
