### ISSUE TITLE
Problems with type hinting

### ISSUE THREAD

**Issue by mosesontheweb** [NilsJPWerner/autoDocstring#103]
Hi,

I recognized that autodocstring has problems with type hinting when using parts of the typing module.

Example:
```python
from typing import Dict, List, Optional
...
def insert_release_info(release_info: Dict[str, str], 
    latest_release: List[str]) -> Optional(int):
```
generates
```python
    """[summary]
    
    Arguments:
        release_info {Dict[str, str], latest_release} -- [description]
    
    Returns:
        [type] -- [description]
    """
```
The neither return type nor the variable `latest_release` are recognized at all.

Not really a big deal, sometimes a bit annoying, just for your records.

Regards, Thomas

**Comment by mosesontheweb** [comment]
EDIT:
When using it this way:
```python
def update_latest_release_information(
        inserted_id: int,
        last_entry: List[str]) -> Tuple[str, int]:
        """[summary]
        
        Arguments:
            inserted_id {int} -- [description]
            last_entry {List[str]} -- [description]
        
        Returns:
            Tuple[str, int] -- [description]
        """
it works perfectly. It seems that the problem occurs only when having multiple variables with annotation from typing on the same line.
Regards, Thomas

**Comment by zgoda** [comment]
```python
def load_tds(svc: DBAPI, langcode: str) -> List[str]:  # pragma: nocover
```

The above definition generates only
```
    """[summary]

    :return: [description]
    :rtype: [type]
    """
```

**Comment by NilsJPWerner** [comment]
@zgoda you appear to be experiencing a different problem. Could you open a separate issue with that code?

**Comment by NilsJPWerner** [comment]
@mosesontheweb I looked into your issue and it looks like the cause was that you were using parentheses instead of square brackets in you return type. It looks like the correct usage is to use square [brackets](https://docs.python.org/3/library/typing.html#typing.Optional), so I am unsure if I should change the extension to accept parentheses in the return portion.
