### ISSUE TITLE
Support attributes

### ISSUE THREAD

**Issue by risoms** [NilsJPWerner/autoDocstring#104]
Description
The extension should also be able to support attributes. For example:

```python
def get_input(ido):
    _a = None
    x = None
```
should be documented like:

```python
def get_input(ido):
    """[summary]
    
    Parameters
    ----------
    ido : [type]
        [description]
    
    Attributes
    ----------
    xe : [type]
        [description]
    """
    _a = None
    xe = None
```

**Comment by NilsJPWerner** [comment]
I've never heard of python function attributes. Do you have a link to the relevant documentation?

**Comment by risoms** [comment]
https://www.python.org/dev/peps/pep-0232/

This would also benefit form supporting class attributes.

**Comment by NilsJPWerner** [comment]
From that pep doc, it seems like there is no way to explicitly define a function attribute within a function. They are just settable once the function has been defined. In your example xe is just a variable within the scope of the function. It doesn't seem like you can access it via `get_input.xe`
