### ISSUE TITLE
Docstring only generated with [summary]

### ISSUE THREAD

**Issue by JohnnyXiangyu** [NilsJPWerner/autoDocstring#105]
Hi I'm having this problem generating docstring. When I type the opening docstring quotes, only a [summary] tag is generated. 
Example:
`from flask import Flask, request
...

@app.route('/api/connect', methods=['POST'])
def connect():`

generates:
`    """[summary]
    """`

I tried to change style settings in extension settings but nothing changes. Other settings including extended summary and start on newline still work.

**Comment by NilsJPWerner** [comment]
What is the desired/expected behavior?

**Comment by JohnnyXiangyu** [comment]
> What is the desired/expected behavior?

Hi, I tried to set the format to each of the options included upon installation, but the output doesn't change. I was expecting the full block of formatted docstring, like the one shown in the readme.

**Comment by NilsJPWerner** [comment]
@JohnnyXiangyu the extension fills out the docstring from the parameters in the function signature/definition. Since your flask route has no parameters the docstring will only have a summary block. From my perspective the extension is working as intended. Am I misunderstanding?

**Comment by JohnnyXiangyu** [comment]
@NilsJPWerner Thanks! I didn't know that format is dynamically generated :)
