### ISSUE TITLE
[Question] ipynb files

### ISSUE THREAD

**Issue by austinmw** [NilsJPWerner/autoDocstring#106]
Is there a way to get this to work for `.ipynb` files? By default it seems to only work for standard `.py` files.

**Comment by NilsJPWerner** [comment]
@austinmw are you trying to use the extension in vscode notebook editor mode, or are editing it as a normal file?

**Comment by austinmw** [comment]
In notebook editor mode

**Comment by NilsJPWerner** [comment]
I've tried integrating it in, but there are some oddities to how vscode handles notebooks. I will need to investigate further.

**Comment by NilsJPWerner** [comment]
I don't think this is possible right now. The jupyter mode in vscode is a custom notebook view that doesn't interact with the api in the standard way. I think vscode is standardizing notebook functionality in a future update at which point I may revisit this. For now I will close the issue.
