### ISSUE TITLE
Only summary generated if comment found in function definition line

### ISSUE THREAD

**Issue by zgoda** [NilsJPWerner/autoDocstring#108]
Full docstring is generated normally, with types inferred from hints.

```python
def fun(a1: str, a2: dict) -> str:
    """[summary]

    :param a1: [description]
    :type a1: str
    :param a2: [description]
    :type a2: dict
    :return: [description]
    :rtype: str
    """
    pass
```

But if there is a comment after function definition in the same logical line (it may contain physical line breaks) only summary field is generated:

```python
def fun(a1: str, a2: dict) -> str:  # comment
    """[summary]
    """
    pass
```

This is usual place for code analysis tools to put pragmas, like `pragma: nocover` to skip block from test coverage calculation.

**Comment by jmfederico** [comment]
Happens as well when last type is a String, for instance for a class method returning an instance of itself:

```python
class Class:

    def method(self, a1: str) -> "Class":
        """
        [summary]
        """
```

**Comment by NilsJPWerner** [comment]
@jmfederico wouldn't the return type in that case be?
```python
def method(self, a1: str) -> Class:
```
Is a string constant a valid return type hint?

**Comment by jmfederico** [comment]
> ```python
> def method(self, a1: str) -> Class:
> ```

It is not possible to use `Class` As the return type, as it is not defined yet. The same happens when you return an instance of a class that is defined after the one you are typing.

In that case you need to use a string. That means you are returning an instance of that class.

**Comment by jmfederico** [comment]
@NilsJPWerner https://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self

**Comment by zgoda** [comment]
@jmfederico 

```python
from __future__ import annotations
```

**Comment by jmfederico** [comment]
@zgoda thanks. For Python 3.6 is there another option?
