### ISSUE TITLE
Docstring problem

### ISSUE THREAD

**Issue by collins73** [NilsJPWerner/autoDocstring#112]
When I try to use this extension I get the following \\\ errors:
bouncyball = BouncyBall(100, 6, "Xbox")
    \"\"\"
    
    Keyword arguments:
    argument -- description
    Return: return_description
    \"\"\" 
    

bouncyball.brand = "Nintendo"

**Comment by NilsJPWerner** [comment]
What is your expected result?

**Comment by collins73** [comment]
The expected result should be:

"""
with content

"""

there should be no "\"\"\"
                               "\'\'\"
with errors

**Comment by hadisotudeh** [comment]
Did you try the shortcut (Ctrl + Shift + 2)?

**Comment by collins73** [comment]
Actually,

It appears to be fixed now. I did not need to execute the command you
mentioned above. Thanks.
