### ISSUE TITLE
Question: PEP 257 Support

### ISSUE THREAD

**Issue by FredHappyface** [NilsJPWerner/autoDocstring#115]
First of all, what a fantastic project! This makes python development in VSCode that bit easier 😄 

PEP 257 support has been coming soon for quite some time. So I was wondering if this is still on the roadmap?

Thanks

**Comment by NilsJPWerner** [comment]
It's on the docket. If you create a [custom template](https://github.com/NilsJPWerner/autoDocstring#custom-docstring-templates) format for it you can pr it and I'll merge it in.

**Comment by FredHappyface** [comment]
Sounds grand, I'll get on that.

Hmm... I swear there were more examples of what the format was out there

**Comment by FredHappyface** [comment]
I've had a pretty good look for examples on this. I was sure that VSCode had a linter for this that was throwing warnings with just about every style but now I am unable to find this. If anyone does happen to have, or know of example could you drop that here and I'll get to work on the template.
