### ISSUE TITLE
Wrong indentation if function body is missing

### ISSUE THREAD

**Issue by NilsJPWerner** [NilsJPWerner/autoDocstring#117]
**autoDocstring Version:** 0.5.0
**Operating System:** MacOS 10.15.4
**Vscode Version:** 1.44.2

**Code:**
```python
def a_function(a, b):
# generate here
```

**Expected:**
```python
def a_function(a, b):
    """[summary]

    :param a: [description]
    :type a: [type]
    :param b: [description]
    :type b: [type]
    """
```

**Actual:**
```python
def a_function(a, b):
"""[summary]

:param a: [description]
:type a: [type]
:param b: [description]
:type b: [type]
"""
```

**Comment by tbright17** [comment]
Same here. Please fix it.

**Comment by kamatimaru** [comment]
I found the same thing happens with class.

autoDocstring Version: 0.5.0
Operating System: MacOS 10.15.4
Vscode Version: 1.44.2

Code:

```python
ClassA:
# generate here
```

Expected:

```python
class ClassA:
    """
    [summary]
    """
```

Actual:

```python
class ClassA:
"""
[summary]
"""
```

**Comment by marcelo-villa-p** [comment]
Same things happens to me.

autoDocstring Version: 0.5.1
Operating System: Ubuntu 18.04.4
Vscode Version: 1.44.2

**Comment by faulknermano** [comment]
For more info: If function body has existing indentation:
```
def test(argv):
    pass
```

Then docstring is idented properly.
```
def test(argv):
    """[summary]

    [extended_summary]

    :param argv: [description]
    :type argv: [type]
    """
    pass
```

But when empty, then identation is same level as `def` itself.

**Comment by ShuhuaGao** [comment]
Same issue for me. Please fix it. Thank you very much.
