### ISSUE TITLE
Doc String not generated in 0.5.0, was working in 0.4.0

### ISSUE THREAD

**Issue by Bill-Fujimoto** [NilsJPWerner/autoDocstring#118]
**Describe the bug**
The doc string template is not generated below the function def after entering """.  This was working a few days ago, I noticed an update today, April 21, 2020 was pushed.  
I reverted to version 0.4.0 and then it worked as expected.

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.0
- Operating System: Windows 10, version 2004
- Vscode Version: 1.44.2

**Original Code (with line to generate on):**
```python
def single_slug(request, single_slug):
    categories = [c.category_slug for c in TutorialCategory.objects.all()]
```

**Expected Result:**
```python
```

**Actual Result:**
```python
def single_slug(request, single_slug):
    """
    
    categories = [c.category_slug for c in TutorialCategory.objects.all()]
```

**Additional context**

**Comment by NilsJPWerner** [comment]
That is strange. Do you get a CompletionItem like the one in this screenshot? 

![image](https://user-images.githubusercontent.com/10968348/79934536-c0ff5400-8420-11ea-9efb-0fdbfe77e0db.png)

Are you able to use the command `Generate Docstring` from the command palette?

**Comment by Bill-Fujimoto** [comment]
I reinstalled 0.5 and tried the Generate Docstring command, this **does** work, but using """ below the def does not work.  So probably not a major bug.

**Comment by NilsJPWerner** [comment]
I will get a hold of a windows computer and test it. There may be differences in how vscode checks for completion item activation events across operating systems. I would also test it with only the autodocstring extension activated and without any options specified in vscode preferences (you can just comment them out). There might be a setting that is messing with the completion items api.

**Comment by ByteArts** [comment]
I've seen the same issue on my Win8.1 machine. On my Mac, it works fine.

**Comment by ankitbko** [comment]
Not working in mine. `Ctrl+Shit+2` works but no autocompletion after `"""`

**Comment by Lucbus** [comment]
I made some tests and for me the `"""` works if the Line ending is set to LF. In scripts where the line ending is set to CRLF  only `Ctrl+Shift+2` works. 
I am using windows 10 as well.

**Comment by HaaLeo** [comment]
Maybe related to #65 
There also different line endings settings were causing the issue.

**Comment by NilsJPWerner** [comment]
Thanks @HaaLeo I will try that.

**Comment by gregchamblin** [comment]
I am on Win 10 Fast ring insider with VSC 1.45 insider.

I receive the following when typing """...

>     """sumary_line
>     
>     Keyword arguments:
>     argument -- description
>     Return: return_description
>     """

Summary is obviously spelled incorrectly, but I am not too worried about that. If I use ctrl+shift+2, I get the docstring that is expected.

Thank you!
