### ISSUE TITLE
Add support for Doxygen

### ISSUE THREAD

**Issue by daluar** [NilsJPWerner/autoDocstring#120]
Hi
I know that this is a long shot, but would it be possible to add support for doxygen?
Sometimes it is required for me at work and I live would be a little bit better if this extension had support for this system of documentation
If not, how could I add it myself?
Thanks for the great work

**Comment by NilsJPWerner** [comment]
You could try to recreate the docstring format with the custom docstring templates: https://github.com/NilsJPWerner/autoDocstring#custom-docstring-templates

**Comment by danlub** [comment]
That's great! I will try in the next days and report back. If it works, I will post the snippet here

**Comment by danlub** [comment]
This template seems to create a good docstring

```
{{! Doxygen Docstring Template }}
!
@brief {{summaryPlaceholder}}

{{extendedSummaryPlaceholder}}

{{#parametersExist}}
{{#args}}
@param {{var}} ({{typePlaceholder}}): {{descriptionPlaceholder}}
{{/args}}
{{#kwargs}}
@param {{var}} ({{typePlaceholder}}, optional): {{descriptionPlaceholder}}. Defaults to {{&default}}.
{{/kwargs}}
{{/parametersExist}}

{{#returnsExist}}
{{#returns}}
@return ({{typePlaceholder}}): {{descriptionPlaceholder}}
{{/returns}}
{{/returnsExist}}

{{#exceptions}}
@throws {{type}} {{descriptionPlaceholder}}
{{/exceptions}}
```

**Comment by NilsJPWerner** [comment]
If you create a pr I will merge it in as a standard option.

**Comment by danlub** [comment]
Great!
Let me test it for a couple of days before doing that
