### ISSUE TITLE
doctring for single quotes does not get autogenerated

### ISSUE THREAD

**Issue by alexanderdevm** [NilsJPWerner/autoDocstring#125]
VSCcode: 1.44.2
OS: Mac OS 10.15.4
Language: Python
docstringFormat: google
Quote styles config: `"autoDocstring.quoteStyle": "'''",` is set.

In build 0.4, i could use `'''` to generate doc script block

in build 0.5.x, by typing `'''` it doesn't do anything, i need press crtl+shift+2 to generate doc string.

**Comment by NilsJPWerner** [comment]
I will fix this.
