### ISSUE TITLE
Docstring not indenting on generation

### ISSUE THREAD

**Issue by HalperinOrganix** [NilsJPWerner/autoDocstring#130]
I might just be an idiot but for some reason when I generate a docstring it doesn't seem to indent with the class or function.

VSCode on Windows.

![Code_pUAETbaZU9](https://user-images.githubusercontent.com/7541968/81487776-b5c86880-9215-11ea-8d44-328c150a700a.png)

**Comment by NilsJPWerner** [comment]
Duplicate of #117
