### ISSUE TITLE
press enter after triple quotes (''') doesn't work

### ISSUE THREAD

**Issue by seungbaeji** [NilsJPWerner/autoDocstring#134]
**Describe the bug**
Press enter after triple quotes (''') doesn't work. 
but `cmd+shift+2` works well.

my current setting is below:
```
"setting": {
...
	"autoDocstring.docstringFormat": "google",
	"autoDocstring.quoteStyle": "'''"
}

```

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.1
- Operating System: macOS catalina
- Vscode Version: 1.45.0

**Original Code (with line to generate on):**
```python
# generate on this line
```

**Expected Result:**
```python
```

**Actual Result:**
```python
```

**Additional context**

**Comment by NilsJPWerner** [comment]
Dupicate of #125
