### ISSUE TITLE
Remove trailing whitespace from empty newlines for pylint compliance

### ISSUE THREAD

**Issue by jykong** [NilsJPWerner/autoDocstring#14]
It'd be great if the empty newlines generated by autoDocstring didn't contain trailing whitespaces. I'm getting tired of pressing backspace to delete them to make pylint happy.

**Comment by NilsJPWerner** [comment]
Hi this is a problem with vscode's handling of snippets in general. I've opened an issue at it's repo: https://github.com/Microsoft/vscode/issues/40613 For a temporary fix I would suggest turning on the remove trailing spaces functionality in vscode to avoid having to remove them manually.
