### ISSUE TITLE
Push new version to marketplace?

### ISSUE THREAD

**Issue by bastienboutonnet** [NilsJPWerner/autoDocstring#141]
#140 was merged and adds support for quoted type hints.

Do you have any plans to push the new code on the marketplace or are you waiting to bundle a few more changes? If so, do you know when you might plan on pushing? A few colleagues of mine are waiting to turn type guessing back on and leverage the new feature so I thought I'd check.

**Comment by NilsJPWerner** [comment]
I want to bundle a couple other changes, but will push later tonight.
