### ISSUE TITLE
Docstring generated with failed syntax \"\"\" instead of """ 

### ISSUE THREAD

**Issue by exowanderer** [NilsJPWerner/autoDocstring#150]
**Describe the bug**
When I type `"""` directory after the function name, the output from `autoDocstring` is not at all what is shown in the preview (via VSCode or the GitHub). I tried this via 2 different operating systems (Windows 10 and Ubuntu 18.04 via WSL2)

(1) The `"""` is converted to `\"\"\"` above and below the docstring.
(2) The configuration of the docstring itself is not remotely what is shown in the preview on GitHub (or elsewhere).

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.3 (install via VSCode Marketplace)
- Operating System1: Ubuntu 18.04 via Window Subsystem for Linux 2
- Operating System2: Windows 10
- Vscode Version: 1.46.1

**Expected Result:**
```python
def function_name(thing1, thing2):
    """[summary]

    Args:
        thing1 ([type]): [description]
        thing2 ([type]): [description]

    Returns:
        [type]: [description]
    """
    return 2 * thing
```

**Actual Result:**
```python
def function_name(thing1, thing2):
    \"\"\"sumary_line
    
    Keyword arguments:
    argument -- description
    Return: return_description
    \"\"\"
    return 2 * thing
```

**Additional context**
I did not edit any configuration files. I installed the extension via the VSCode marketplace, and then tested it, which generated the false syntax shown above.

**Comment by NilsJPWerner** [comment]
These seem to be coming from a different extension called flask_snippets: https://github.com/jleonra/flask-snippets/blob/master/snippets/controls.cson#L4 

When you activate the popover, make sure you use the `Generate Docstring` option rather than the `ML docstring (flask-snippets)` option. 

![image](https://user-images.githubusercontent.com/10968348/86131905-3c7e2100-bab4-11ea-9f4c-867c38035359.png)

**Comment by exowanderer** [comment]
That was exactly the problem. Thank you so much! I had no idea that I even (a) installed flask snippets and (b) that """ activated the flask snippets.

Thank you for such a swift reply. Your extension is one of my favorites!
