### ISSUE TITLE
Docstring extension not working in Notebook View

### ISSUE THREAD

**Issue by aaronsmith1234** [NilsJPWerner/autoDocstring#154]
**Describe the bug**
When coding in ipynb files, the autodocstring extension doesn't work.

**Versions (please complete the following information):**
- autoDocstring Version: v0.5.3
- Operating System: Windows 10
- Vscode Version: 1.47.2

**Comment by mihinsumaria** [comment]
I am seeing similar behavior for the following versions:

- autoDocstring Version: v0.5.3
- Operating System: macOS 10.15.6
- VSCode Version: 1.50.0

**Comment by AmauryFaure** [comment]
Hello, I too am seeing this issue

Versions: 
- autoDocstring Version : v0.5.4
- OS : Ubuntu 20.04.1 LTS 
- VSCode Version : 1.51.1

**Comment by NilsJPWerner** [comment]
This has been covered before. The required apis might have been added so I will look into whether it is feasible now https://github.com/NilsJPWerner/autoDocstring/issues/106

**Comment by AmauryFaure** [comment]
Okay thanks !
