### ISSUE TITLE
Feature Request: Starlark support

### ISSUE THREAD

**Issue by UebelAndre** [NilsJPWerner/autoDocstring#158]
Hey, I understand this extension is focused on python but.... Would it be possible to extend this to [starlark](https://github.com/bazelbuild/starlark/blob/master/spec.md) as well. The language is extremely similar to Python so I thought it would be fairly easy but any author/contributor would for sure know better than me 😅 

Happy to accept a `Won't Do` response, just thought I'd ask. If this is the case though, might someone have any suggestions on where to start?

**Comment by IniasP** [comment]
I'm not the dev but if function and class definitions look exactly like Python's you should look at `src/extensions.ts` where it calls `vs.languages.registerCompletionItemProvider` to register a python CompletionItemProvider and check if adding the exact same thing for starlark files works out of the box. If starlark is compliant with [PEP 484](https://www.python.org/dev/peps/pep-0484/), type hints should work too.

If you're new to this, you might want to read up on [debugging vs code extensions from vs code itself](https://vscode.readthedocs.io/en/latest/extensions/debugging-extensions/#:~:text=You%20can%20easily%20run%20your,view%20or%20the%20Debug%20Console%20.), which should be very helpful.

Not-so unrelated: I submitted a pull request for something else 20 days ago but the dev seems to be inactive for now.

**Comment by UebelAndre** [comment]
Thanks! I opened a pull request that implements this feature request (#159). Again, I understand if this isn't something the Author wants to support but I'm really they don't mind 😄

**Comment by UebelAndre** [comment]
This is closed now that #159 is merged. Thanks @NilsJPWerner !!!
