### ISSUE TITLE
Eliminate all unnecessary empty lines

### ISSUE THREAD

**Issue by tbrodbeck** [NilsJPWerner/autoDocstring#172]
It is great that VS Code support automatic docstring generation in Python. I am just missing one Docstring Format that is optimal for my needs. It would also be helpful to fully customize and create your own Docstring format to choose from.

# Format right now (using Google format)
```
  """[summary]

  Args:
      lmNameOrID (str): [description]
      corpora (list, optional): [description]. Defaults to [].
      grammars (list, optional): [description]. Defaults to [].
      wordsFiles (list, optional): [description]. Defaults to [].
      corporaPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/corpus/'.
      grammarsPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/grammar/'.
      wordsPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/custom_words/'.
      retrain (bool, optional): [description]. Defaults to False.
  """
```
# Improved format
```
  """[summary]
  Args:
      lmNameOrID (str): [description]
      corpora (list, optional): [description]. Defaults to [].
      grammars (list, optional): [description]. Defaults to [].
      wordsFiles (list, optional): [description]. Defaults to [].
      corporaPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/corpus/'.
      grammarsPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/grammar/'.
      wordsPath (str, optional): [description]. Defaults to 'agent-assist-speech-to-text/in/custom_words/'.
      retrain (bool, optional): [description]. Defaults to False."""
```
This is still a viable Google Format docstring I prefer because it simply takes less space than the original Google format. It would be great if this would be supported by VS Code in some way.

The first empty line is possible to eliminate with a custom template but not the the second. Can you add a way to eliminate it as well?

**Comment by NilsJPWerner** [comment]
Custom docstrings are already supported. I am going to keep the current google format in the included docstring formats since it if closer to the official spec.

**Comment by tbrodbeck** [comment]
Hey Nils. Thanks for the input. So I created my own docstring template. Thats cool.

But there is one issue I noticed:
I would like to eliminate the final newline like this:
```
    """[summary]"""    
```
But only this is possible:
```
    """[summary]
    """    
```
