### ISSUE TITLE
generate arguments add a blank line

### ISSUE THREAD

**Issue by visonforcoding** [NilsJPWerner/autoDocstring#18]
![image](https://user-images.githubusercontent.com/4387302/35318857-33ba64be-0118-11e8-80b6-246646726575.png)

last picture is auto generate.

![image](https://user-images.githubusercontent.com/4387302/35318893-6a7aafcc-0118-11e8-85ff-5b49622560a0.png)

last picture ,i change something  ,add blank line .be more beautiful

**Comment by Bloodmallet** [comment]
This might be an interference from other extensaions. On my end it works fine like this: 
![image](https://user-images.githubusercontent.com/9075987/36484558-fbecf304-1719-11e8-8d6d-a54de9f2c11f.png)

**Comment by visonforcoding** [comment]
ok.I will check it. thank you.
