### ISSUE TITLE
Error with arg annotation

### ISSUE THREAD

**Issue by WXZhao7** [NilsJPWerner/autoDocstring#194]
**Describe the bug**
The autoDocstring can't work when the arg's type istring with `"`.

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.4
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS and version: Ubuntu 20.04 focal
Python version: 3.8.10.final.0
Type of virtual environment used: conda 4.10.1
Value of the python.languageServer setting: pyLance

**Original Code (with line to generate on):**
```python
def autodoc(par1: "aha" = None, par2: "aha" = None) -> "aha":
    """ #select Generate docstring
```

**Expected Result:**
```python
def autodoc(par1: "aha" = None, par2: "aha" = None) -> "aha":
    """autodoc [summary]

    [extended_summary]

    Args:
        par1 ("aha", optional): [description]. Defaults to None.
        par2 ("aha", optional): [description]. Defaults to None.

    Returns:
        "aha": [description]
    """
    pass
```

**Actual Result:**
```python
def autodoc(par1: "aha" = None, par2: "aha" = None) -> "aha":
    """autodoc [summary]

    [extended_summary]
    """
    pass
```

**Comment by WXZhao7** [comment]
the similar case with type endwith `()`:
````python
def autodoc(par: obspy.Stream() = default, par: "int" = default,) -> obspy.Stream():
    """autodoc [summary]

    [extended_summary]

    Args:
        par (obspy.Stream, optional): [description]. Defaults to default, par:"int"=default, )->obspy.Stream(.
    """
````

**Comment by NilsJPWerner** [comment]
The first issue is fixed now, the second example is not valid python. Pylance reports `Illegal type annotation: call expression not allowedPylance[reportGeneralTypeIssues]`
