### ISSUE TITLE
Numpy and Sphinx 

### ISSUE THREAD

**Issue by patricieni** [NilsJPWerner/autoDocstring#2]
Hello Nils, 

Thanks for the package, it's great! I was wondering whether you have a timeline for a minimal Numpy and Sphinx integration?

**Comment by NilsJPWerner** [comment]
Hey, I will start adding them this weekend. Should be done within a week.

**Comment by NilsJPWerner** [comment]
Sorry for the huge delay. Numpy and sphinx is now added.

**Comment by patricieni** [comment]
Great!
