### ISSUE TITLE
How to change the formatting of Visual Studio Codes docstring preview?

### ISSUE THREAD

**Issue by JakobHavtorn** [NilsJPWerner/autoDocstring#20]
How would one go about making Visual Studio Code recognize e.g. the Google docstring format in its docstring ""preview on hover" functionality?

Google searching has left my question unanswered.

**Comment by yeetor** [comment]
i have the same question.

**Comment by NilsJPWerner** [comment]
Hi Jakob, I think that the hover operation is a little screwy in general for python. I would suggest opening up an issue at the python vscode extension repository: https://github.com/Microsoft/vscode-python 

I will close this issue for now, since it's not directly related to the extension.
