### ISSUE TITLE
Support for PEP 484

### ISSUE THREAD

**Issue by Kasperfred** [NilsJPWerner/autoDocstring#22]
Implementing [PEP 484](https://www.python.org/dev/peps/pep-0484/) would let the extension parse function-annotations to automatically fill in types. 

For example, the generated doc-string for this annotated function is currently:
```
def foo(bar: str) -> str:
	"""[summary]
	
	Arguments:
		bar: str {[type]} -- [description]
	
	Returns:
		[type] -- [description]
	"""

	return bar
```

When it could have generated:
```
def foo(bar: str) -> str:
	"""[summary]
	
	Arguments:
		bar {str} -- [description]
	
	Returns:
		str -- [description]
	"""

	return bar
```

**Comment by NilsJPWerner** [comment]
This is now implemented. Sorry for the delay! :)
