### ISSUE TITLE
Any way to get tab placeholders back after the highlighting is "lost"?

### ISSUE THREAD

**Issue by sgbaird** [NilsJPWerner/autoDocstring#227]
For example, it seems like if I accidentally type past the summary line, then the highlighting goes away, and I lose the ability to tab through the rest of the placeholders. No worries if not, just wanted to check if I was missing something.

**Comment by NilsJPWerner** [comment]
I think this is a limitation of vscode. autoDocstring uses the snippets api so if there isn't anything in the vscode docs mentioning recovering the placeholder highlighting I am unable to really do anything: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by sgbaird** [comment]
Ok, thank you!
