### ISSUE TITLE
Support for PEP 526

### ISSUE THREAD

**Issue by stephen-bunn** [NilsJPWerner/autoDocstring#24]
With the addition of support for PEP 484 (#22, #23), support for [PEP 526](https://www.python.org/dev/peps/pep-0526/) would also be very desirable.
This would have to take into consideration substitutions for [typing](https://docs.python.org/3/library/typing.html)'s type declarations.

For example:
```python
from typing import (List,)

def foo(bar: List[str]) -> str:
	"""[summary]
	
	Arguments:
		bar {list(str)} -- [description]
	
	Returns:
		str -- [description]
	"""

	return bar[0]
```

**Comment by Kasperfred** [comment]
I believe #25 fixes this.

**Comment by NilsJPWerner** [comment]
This is now implemented. Sorry for the delay! :)
