### ISSUE TITLE
Erases previously existing docstring if editing first line

### ISSUE THREAD

**Issue by u2berggeist** [NilsJPWerner/autoDocstring#26]
When I'm editing a docstring that has already been filled out, and hit `Enter` when at the first line of the docstring, it erases all of the docstring and replaces it with the docstring template.

I can fix it with a quick `Ctrl + z`, but it really shouldn't happen in the first place.

In my mind, it should really just create a new docstring template rather than erasing the old one, but I'm not familiar with how the extension works, so that might not be feasible/desirable.

**Comment by NilsJPWerner** [comment]
This seems like a bug. Will investigate.

**Comment by NilsJPWerner** [comment]
I think the latest update should solve this problem. At least I haven't been able to recreate it with the new code. I'm going to close the issue for now. Please reopen if it is still happening for you.
