### ISSUE TITLE
Empty doctrings being generated

### ISSUE THREAD

**Issue by sharmuz** [NilsJPWerner/autoDocstring#275]
**Describe the bug**
All docstrings being generated are empty.

**Versions (please complete the following information):**

-   autoDocstring Version: 0.6.1
-   Operating System: macOS Sonoma 14.1.2
-   Vscode Version: 1.85.0

**Original Code (with line to generate on):**

```python
def my_func(foo: str, bar: int) -> bool:
    return True
```

**Expected Result:**

```python
def my_func(foo: str, bar: int) -> bool:
    """_summary_
 
    Args:
        foo (str): _description_
        bar (int): _description_
 
    Returns:
        bool: _description_
    """
    return True
```

**Actual Result:**

```python
def my_func(foo: str, bar: int) -> bool:
    """
    """
    return True
```

**Debug log:**
I set log level to Debug but no output...

```
[INFO 10:41:18.823] autoDocstring was activated
```

**Additional context**
Issue has been occurring since about 2 weeks ago. In that time my Python extension and macOS were updated.

**Comment by sharmuz** [comment]
Reinstalled the extension and working fine now! Putting this down to my fiddling with settings / updates. I can't live without this <3

**Comment by zhanwenchen** [comment]
Reinstalled many times with or without reload. Still only the '''_summary_ tag''' generated.
