### ISSUE TITLE
Generation errors in creating docstring

### ISSUE THREAD

**Issue by Modelmat** [NilsJPWerner/autoDocstring#3]
![image](https://user-images.githubusercontent.com/25718989/34474215-3ad40272-efd0-11e7-8f6c-5f1b15ff917d.png)
**Issues:**
- Doesn't detect that it hasn't been indented
- Doesn't auto-detect type hinted types (thinks they are part of the name)
- Doesn't detect the return (<sup>[1]</sup> does)
- Argument {f} doesn't appear in keyword arguments
- **kwargs isn't recognised as a keyword argument

**Feedback:**
- Note that *args is a list (auto-detection) and **kwargs is a dict . Anything that starts with `*`, or `**` does this too.

<sup>[1]</sup>:
![image](https://user-images.githubusercontent.com/25718989/34474239-8c2d2df6-efd0-11e7-888f-22e947d60fd2.png)

**Comment by NilsJPWerner** [comment]
I will take a look at what's causing it.

**Comment by Modelmat** [comment]
I'm not getting anything now.
Just the [summary] @NilsJPWerner

**Comment by Modelmat** [comment]
It is because it is a keyword argument.

**Comment by NilsJPWerner** [comment]
Hey Modelmat, I am working on a new parser that will solve this issue in this [pr](https://github.com/NilsJPWerner/autoDocstring/pull/13/commits). The current one is based on unwieldy regex that isn't great for strings and tuples in kwarg defaults. The one I'm working on is token based and won't have problems dealing with string kwargs.
