### ISSUE TITLE
Docstrings conflict with Pylint C0303: Trailing Whitespace

### ISSUE THREAD

**Issue by niderhoff** [NilsJPWerner/autoDocstring#34]
The newlines which are pasted by the docstring-extension are indented and thereby cause an warning when using pylint with the C0303 message enabled.

<img width="154" alt="trailing" src="https://user-images.githubusercontent.com/5991543/37146559-64fc8a16-22c4-11e8-98a1-d837db3f9fa3.PNG">
<img width="164" alt="trailing2" src="https://user-images.githubusercontent.com/5991543/37146560-6516da92-22c4-11e8-8ea1-4dc93a348ec9.PNG">

**Comment by NilsJPWerner** [comment]
Hi @niderhoff unfortunately this is a limitation of vscode: https://github.com/Microsoft/vscode/issues/40613 I may attempt to create a hacky solution but it won't be perfect until microsoft fixes snippet spacing.

**Comment by saponas** [comment]
FWIW, I am trying to submit a PR to code for a fix/setting: https://github.com/Microsoft/vscode/pull/55336

**Comment by BobAnkh** [comment]
Hi, when i use autodocstring now i still meet with the problem **blank line contains whitespace flake8(W293)**, using default format. 

Is there anything i should do or configure to fix it? Or i should wait for the problem to be completely fixed?
Thanks
![image](https://user-images.githubusercontent.com/44333669/76637102-1b390980-6585-11ea-8af3-edea0558593a.png)
