### ISSUE TITLE
numpy format generates 'Parameters' keyword with a colon

### ISSUE THREAD

**Issue by akochepasov** [NilsJPWerner/autoDocstring#35]
numpy format generates 'Parameters' keyword with a colon, but numpy document specifies it without the colon:
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard

**Comment by NilsJPWerner** [comment]
Thanks will fix.

**Comment by NilsJPWerner** [comment]
Fixed https://github.com/NilsJPWerner/autoDocstring/commit/406b341aa073ee58c2c4db0e2bb0c448c4508986
