### ISSUE TITLE
pre-fill method name in front of summary

### ISSUE THREAD

**Issue by petrdanecek** [NilsJPWerner/autoDocstring#36]
Hi there,

thanks for great plugin. Obviously I start method docstring with method name. Would it be possible to have the option to pre-fill the method name in front of summary?
I would also think about some templating system which allows customizing the auto-generated docstrings.

Example of my docstring:

```
 def is_authorized(self, ticket_id):
        """
        is_authorized returns true for users been authorized
        to retrieve RT update.

        :param ticket_id:   int:    Ticket number.
        :return:            bool:   True for authorized user, false otherwise.
        """
```

**Comment by NilsJPWerner** [comment]
Thanks! I can add that as an option.

**Comment by NilsJPWerner** [comment]
Added in 0.2.1 as option autoDocstring.includeName
