### ISSUE TITLE
This extension is consuming more than 200MB [serious issue]

### ISSUE THREAD

**Issue by wongjiahau** [NilsJPWerner/autoDocstring#37]
I think there might be an error in your deployment, because when I install this extension, I found out that its test code are also included, you can find it at the following directory:
```
~/.vscode/extensions/njpwerner.autodocstring-0.2.0/.vscode-test
```
This folder is taking 280MB in my laptop.  
Therefore you should exclude it on the next deployment.

**Comment by NilsJPWerner** [comment]
Ahh, yeah that is the vscode node module that is used for testing. I will update the extension tonight. Thanks for finding that.

**Comment by wongjiahau** [comment]
No prob bro.
