### ISSUE TITLE
Docstring can be generated at end of tripe quotes

### ISSUE THREAD

**Issue by Modelmat** [NilsJPWerner/autoDocstring#4]
If I make a function:
```python
def foo(bar):
    """[summary]
    
    Arguments:
        bar {[type]} -- [description]
    """
    ```
And I hit enter after the last tripe quotes, this happens:
```python
def foo(bar):
    """[summary]
    
    Arguments:
        bar {[type]} -- [description]
    """[summary]
    """
    ```
Check for this please! 
This could be fixed by just checking that there is no docstring anywhere else in the function, would also prevent the issue of second triple quotes doing this too.

**Comment by NilsJPWerner** [comment]
Thanks for brining this to my attention. Will fix asap

**Comment by NilsJPWerner** [comment]
This has been fixed in the latest version.
