### ISSUE TITLE
Which key could be used to navigate through each input field highlighted?

### ISSUE THREAD

**Issue by citanda** [NilsJPWerner/autoDocstring#43]
Hi, this plugin is very cool, but in your demonstration GIF, the cursor first stops at [summary], and then the content you input replaced [summary], and then the cursor just jumped to the next input field [type]. However, I tried 'enter' or 'tab' on my code, it just keeps editing [summary] and I could not jump to the next input field.

I'm using macOS 10.13.4, VSCode 1.22.2. I wonder which key or key combination I should use to navigate through each input field that this plugin highlighted?

Thank you very much.

**Comment by NilsJPWerner** [comment]
I'm sorry I only got to this now. Do you still have this issue? This sounds like an issue with vscode snippets configuration.

**Comment by kgco** [comment]
Same problem to me? Is there any solutions now?

**Comment by NilsJPWerner** [comment]
@kgco are you able to get user defined snippets to work like in the vscode docs: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by Chris-zixuan** [comment]
> @kgco are you able to get user defined snippets to work like in the vscode docs: https://code.visualstudio.com/docs/editor/userdefinedsnippets

I had the same problem，I have reset the vscode Settings to ensure that no other issues interfere，i reinstall autodocstring，Enable it with "editor.tabCompletion": "on"。But  still can't jump with tab。

setting.json
`
{
    "editor.tabCompletion": "on"
}
`
