### ISSUE TITLE
Semicolon ":" appearing after "Parameters" and no blank line exists before "Raises" in NumPy format

### ISSUE THREAD

**Issue by sglvladi** [NilsJPWerner/autoDocstring#44]
Hi there,

Let me start by saying that you've done a great job with this package! The amount of time I have saved on documentation since I started using it is unreal. 👍 

Having said that, I think there might be a small bug which causes a semicolon to be printed after "Parameters", under numpy format. Here is an example generated docstring:

``` python
@ndim.setter
    def ndim(self, ndim):
        """[summary]
        
        Parameters:
        ----------
        ndim : {[type]}
            [description]
        Raises
        ------
        TypeError
            [description]
        ValueError
            [description]
        
        """
        ......
```

Also it seems that the isn't a blank line between the "Parameters" and "Raises" sections.

Obviously, these are not big issues, but I thought I'd mention them in case they're easy to polish out.

**Comment by NilsJPWerner** [comment]
Thanks for the kind words! Fixed in most recent version. Update to 0.2.1 to see changes take affect.
