### ISSUE TITLE
Docstring generation is not sensitive to location in file

### ISSUE THREAD

**Issue by arewm** [NilsJPWerner/autoDocstring#47]
When I type a triple-quote `"""` and then press enter anywhere in the file, the following docstring template is generated.

```
"""[summary]
"""
```

The template should only be generated if the triple quotes are typed below a function.

**Comment by NilsJPWerner** [comment]
Hi @arewm, this is intentional. I mirrored the functionality of the popular sublime extension docBlockr. Is this behavior undesired?

**Comment by arewm** [comment]
I thought that the autoDocstring was being inserted when creating multi-line strings, but I cannot reproduce the behavior now. I will close this issue, thanks!
