### ISSUE TITLE
Option to turn off type generation entirely

### ISSUE THREAD

**Issue by jdb8** [NilsJPWerner/autoDocstring#48]
Hi there, great extension! I'm wondering if you'd be willing to add an option which completely disables the generation of type information inside the generated docstrings. I only have experience with sphinx, so I'm not sure how the other docstring types would look, but since my code is using type annotations I tend to write my docstrings like this:

```python
def foo(some_param: str) -> int:
    """Some function.
    
    :param some_param: the thing that does the other thing
    :return: some meaning of life or whatever
    """
    return 42
```

(omitting the types entirely, since it's possible to generate the sphinx docs using a plugin such as https://pypi.org/project/sphinx-autodoc-annotation/ or https://github.com/agronholm/sphinx-autodoc-typehints).

Happy to help with a PR if you're ok with the idea (although, I'd probably need to research if the other docstring types work without type information).

**Comment by Stigjb** [comment]
This would be a nice option. I have used Sphinx with Google style docstrings, and can confirm that they also work well with plugins that insert the type from type hints.

**Comment by balsagoth** [comment]
I' can help with this PR. @jdb8  did you already started something?

**Comment by jdb8** [comment]
@balsagoth I didn't get around to working on it. Go for it!

**Comment by NilsJPWerner** [comment]
Hi there, sorry for the huge delay in responding to this (I don't use python day to day anymore). I am working on a new update that will take care of this.

**Comment by NilsJPWerner** [comment]
This is now possible by creating your own template that excludes the {{type}} tags. You can just copy the existing [sphinx template](https://github.com/NilsJPWerner/autoDocstring/blob/master/src/docstring/templates/sphinx.mustache) and remove all of the {{type}} & {{typePlaceholder}} tags.
