### ISSUE TITLE
How to use  ''' instead of """  ?

### ISSUE THREAD

**Issue by eromoe** [NilsJPWerner/autoDocstring#49]
Hello, I intend to use ' over " , but I don't know how to do .
Support both would be better,

**Comment by Modelmat** [comment]
If possible, does it generate a docstring upon you typing `'''` and then end it with `"""` or can you just not use `'''`?

**Comment by eromoe** [comment]
`'''` does't generate a docstring,  neither end it with `"""`

**Comment by Modelmat** [comment]
Ok good, I have to fix that. About halfway done 😛 .

**Comment by eromoe** [comment]
Not work again .

version:
![image](https://user-images.githubusercontent.com/3938751/60787708-4d3fd380-a18d-11e9-855a-64f774cb062d.png)

![image](https://user-images.githubusercontent.com/3938751/60787729-5a5cc280-a18d-11e9-9612-35d7a2a4d079.png)
