### ISSUE TITLE
Using `Shift + Windows + 2` impossible

### ISSUE THREAD

**Issue by Modelmat** [NilsJPWerner/autoDocstring#5]
On Windows 10.

Hitting `Shift + Windows + 2` opens the items on my taskbar, and VSCode knows nothing about it.

Please add either an option to configure the keyboard shortcut (preferable) or set it to something else like `Ctrl + Alt + 2`

**Comment by NilsJPWerner** [comment]
Ah, sorry I don't have access to a windows computer so I didn't know that the hotkey was already taken. Will update asap.

**Comment by NilsJPWerner** [comment]
Sorry for the late fix. This issue is resolved in this pr: https://github.com/NilsJPWerner/autoDocstring/pull/10

**Comment by Modelmat** [comment]
Has it been sent yet? This is currently the best docstring maker (I'm sorry to say, but this isn't the best)

**Comment by NilsJPWerner** [comment]
This has been fixed now. Update to the latest extension in the marketplace to see the changes.
