### ISSUE TITLE
flake8 W293:blank line contains whitespace

### ISSUE THREAD

**Issue by SinTod** [NilsJPWerner/autoDocstring#56]
![wx20180823-195053](https://user-images.githubusercontent.com/16619195/44523888-2829aa00-a70e-11e8-83bf-6dc1bb5c5172.png)

**Comment by Modelmat** [comment]
Pretty sure #34 already covers this

**Comment by SinTod** [comment]
@Modelmat so,that is  the vscode's problem, but the new version is always having this bug.

**Comment by SinTod** [comment]
@NilsJPWerner  Thx.
