### ISSUE TITLE
Fails to create snippet when guessTypes: false and no return statement

### ISSUE THREAD

**Issue by Stigjb** [NilsJPWerner/autoDocstring#60]
If `"autoDocstring.guessTypes"` is set to `false`, autoDocstring fails to create a snippet for functions lacking both a return statement and annotated return type.

Example:
```python
def explicit_return(value):
    """[summary]
    
    Args:
        value ([type]): [description]
    
    Returns:
        [type]: [description]
    """

    return print(value)

def no_return(value):
    """

    print(value)
```
After three quotes and Enter, no snippet is inserted in `no_return`.
Confirmed with all four docstring factories.

**Comment by govza** [comment]
And in function with return it ignores false guessTypes
```python
def get_smth(value):
    """
    [summary]
    
    :param value: [description]
    :type value: [type]
    :return: [description]
    :rtype: [type]
    """

    return 0```

**Comment by JarnoRFB** [comment]
I got around this by using a custom template where I removed all the `{{typePlaceholder}}` and still set `"autoDocstring.guessTypes"` to `true`. This does not help much if you want the types, but is ok if you rely on type annotations in the function signature, which is nowadays preferable in my opinion.

**Comment by NilsJPWerner** [comment]
I can't replicate this issue. It may have been solved in a past refactor.
