### ISSUE TITLE
not have "return‘’

### ISSUE THREAD

**Issue by Hypdncy** [NilsJPWerner/autoDocstring#65]
Hello auth:
`
    def test1(msg):
        |index1
        return msg
    def test2(msg):
    |index2
        return msg
`
when I use "ctrl+shift+2" in index1，I can't see return
but I use "ctrl+shift+2" in index2，I can see return
It is not comfortable
I can't speak English,sorry!

**Comment by Hypdncy** [comment]
Hello auth:
def test1(msg): 
    |index1
    return msg 
def test2(msg): 
|index2 
    return msg
when I use "ctrl+shift+2" in index1，I can't see return
but I use "ctrl+shift+2" in index2，I can see return
It is not comfortable
I can't speak English,sorry!

**Comment by Hypdncy** [comment]
Hello auth:
def test1(msg):
&nbsp;&nbsp;&nbsp;&nbsp;|index1
return msg
def test2(msg):
|index2
return msg
when I use "ctrl+shift+2" in index1，I can't see return
but I use "ctrl+shift+2" in index2，I can see return
It is not comfortable
I can't speak English,sorry!

**Comment by KaOzPoNs** [comment]
Hi, i have the same problem... it looks that other """ comments """ affect the correct detection of the docstring...

i have the next function:
def get_db_size(array,bytekey,datatypekey):  
      
    for eachdb in array:
        seq,length = [x[bytekey] for x in eachdb],[x[datatypekey] for x in eachdb]
        floatseq = map(float, seq)
        idx = floatseq.index(max(floatseq))
        lastByte = int(max(floatseq))+(offsets[length[idx]])
        print eachdb
        """ 
        print "seq:%s"%type(seq) 
        print seq
        """
    return lastByte

and when i use the keyboard shortcut, i only get this docString:
"""get_db_size [summary]
      
      [description]
      
      Args:
          array ([type]): [description]
          bytekey ([type]): [description]
          datatypekey ([type]): [description]
      """
without "return"... but... if i remove:
""" 
        print "seq:%s"%type(seq) 
        print seq
        """

then i can get the full docstring:

"""get_db_size [summary]

[description]

Args:
    array ([type]): [description]
    bytekey ([type]): [description]
    datatypekey ([type]): [description]

Returns:
    [type]: [description]
"""

**Comment by z33kz33k** [comment]
In my case, as can be seen below, `Returns` section doesn't get generated if the current cursor location is on a proper level of indentation (inside the functions's block), **but it gets generated if it's on an improper level of indentation** (outside of the function's block, e.g. at a class' or module's level).

![](https://iv.pl/images/58320276845011561550.gif)

> Version: 1.31.1 (system setup)
> Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
> Date: 2019-02-12T02:20:54.427Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 6.1.7601

> autodocstring 0.2.3

Platform: Windows 7 64-bit

**Comment by HaaLeo** [comment]
@z33kz33k This happens only when using CRLF if you use LF it works on indentation level as well. The cause of this behaviour is that [`indentationOf()`](https://github.com/NilsJPWerner/autoDocstring/blob/master/src/parse/utilities.ts#L2) returns "one to much" e.g. 5 instead of 4 for CRLF.
