### ISSUE TITLE
Feature Request: Dense sphinx parameters

### ISSUE THREAD

**Issue by stephen-bunn** [NilsJPWerner/autoDocstring#66]
I typically use the dense version of parameter definition for my docstrings (as documented [here](http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists))

For example I will have the following docstring...

```python
def make_config(name, var_dict, title=None, description=None, **kwargs):
    """ Creates a config instance from scratch.

    :param str name: The name of the config
    :param dict var_dict: The dictionary of config variable definitions
    :param str title: The title of the config, defaults to None, optional
    :param str description: The description of the config, defaults to None, optional
    :return: A new config class
    :rtype: class
    """
```

rather than the long version (which includes `type` lines)...

```python
def make_config(name, var_dict, title=None, description=None, **kwargs):
    """ Creates a config instance from scratch.

    :param name: The name of the config
    :type name: str
    :param var_dict: The dictionary of config variable definitions
    :type var_dict: dict
    :param title: The title of the config, defaults to None, optional
    :type title: str
    :param description: The description of the config, defaults to None, optional
    :type description: str
    :return: A new config class
    :rtype: class
    """
```

Every time `autoDocstring` generates a docstring I have to manually re-edit the docstring to remove `:type {variable}: {type}` and add the type as a prefix to the `:param`.

It would be nice if `autoDocstring` either had a checkbox toggle or a variant on the Sphinx docstring that would save me some time rewriting the generated docstring.

**Comment by NilsJPWerner** [comment]
You should be able to define your own dense version with the new custom templating: https://github.com/NilsJPWerner/autoDocstring#custom-docstring-templates 

Let me know if you have any problems.

**Comment by stephen-bunn** [comment]
I was able to produce what I wanted with the following custom template.

```
{{! Custom Docstring Template }}
{{summaryPlaceholder}}

{{extendedSummaryPlaceholder}}

{{#args}}
:param {{typePlaceholder}} {{var}}: {{descriptionPlaceholder}}
{{/args}}
{{#kwargs}}
:param {{typePlaceholder}} {{var}}: {{descriptionPlaceholder}}, optional, defaults to {{&default}}
{{/kwargs}}
{{#exceptions}}
:raises {{type}}: {{descriptionPlaceholder}}
{{/exceptions}}
{{#returns}}
:return: {{descriptionPlaceholder}}
:rtype: {{typePlaceholder}}
{{/returns}}
```

Thanks for the feature.

**Comment by cassdalton** [comment]
I also want to use the dense sphinx and am trying to recreate what stephen-bunn has done.  I have the latest vscode version and have created a dense.mustache file.  I put the path to that file in the custom template field, and if I mistype that path and start a docstring with """<enter>, I get a message saying that it can't find the file.  But when I type the path correctly and start a docstring, nothing happens.  I get no notification but also no auto docstring.  I am on ubuntu 16.04
