### ISSUE TITLE
Pycharm usage

### ISSUE THREAD

**Issue by rtmatx** [NilsJPWerner/autoDocstring#69]
Hi,

I love this extension and have been using it heavily

Is there any way that it can be ported to Pycharm. I can help anyone if some one can point me to what all things should be done to enable this

Thnaks
Ravi

**Comment by Modelmat** [comment]
This is a huge undertaking. However, I believe PyCharm actually provides this functionality builtin - https://www.jetbrains.com/help/pycharm/creating-documentation-comments.html.

**Comment by NilsJPWerner** [comment]
Thanks for the praise. Pycharm is a jetbrains java based IDE I think, which means that essentially none of the code for this extension could be reused for an equivalent pycharm extension. I'd suggest checking out the builtin functionality that @Modelmat mentioned.
