### ISSUE TITLE
`customTemplatePath` configuration does not substitute VSCode variables

### ISSUE THREAD

**Issue by s-kovacevic** [NilsJPWerner/autoDocstring#72]
In `settings.json` I have:
```
"autoDocstring.customTemplatePath": "${workspaceFolder}/.vscode/pydocstring_template",
```
When I try to generate docstrings I get:
```
AutoDocstring Error: Template could not be found: ${workspaceFolder}/.vscode/pydocstring_template
```

It works with:
```
"autoDocstring.customTemplatePath": "/Users/savo/Documents/Projects/something/something/.vscode/pydocstring_template",
```

I have my other configurations using this same variable with no issues, for example:
```
...
"python.linting.mypyEnabled": true,
"python.linting.mypyArgs": [
    "--config-file", "${workspaceFolder}/src/mypy.ini"
],
...
```
Not sure if this is an extension bug but since other configurations work with the same variable I assumed it is. Let me know if any other info is necessary.

**Comment by s-kovacevic** [comment]
Something [like this](https://github.com/DonJayamanne/pythonVSCode/blob/075d5748fa22d6f7f4f798e46a0d95ecbed12eb5/src/client/common/configSettings.ts#L243) is missing.

**Comment by NilsJPWerner** [comment]
Resolved by: https://github.com/NilsJPWerner/autoDocstring/pull/73
