### ISSUE TITLE
# noqa tag at the end of docstring

### ISSUE THREAD

**Issue by bielovico** [NilsJPWerner/autoDocstring#75]
FEATURE REQUEST

Hello,
I use pylama as a linter. In docstrings it finds  a lot of pycodestyle warnings and errors. The best workaround I found was to add `# noqa` at the end of the docstring.

```
def main():
    """[summary]

    [extended_summary]

    """  # noqa
    pass
```

I hardcoded it into my local docstring_factory.js but I believe that having this in a configuration would be a neat little addition that's easy to implement and can help a lot.

**Comment by NilsJPWerner** [comment]
What are the warnings and errors you get?

**Comment by bielovico** [comment]
Mostly
W293 blank line contains whitespace
W291 trailing whitespace
I couldn't find any other warning or error, could be just these two.
When I think about it, although I find it annoying to check a docstring for this, it is rendered tha same either way. If It's best practice to avoid these in docstring as well, my feature request is probably counterproductive.

**Comment by NilsJPWerner** [comment]
Ah this is because of an underlying vscode issue with whitespaces in vscode snippets. Related issue: https://github.com/NilsJPWerner/autoDocstring/issues/34 

I recommend turning on trim whitespace on save to take care of the errors. Since this is related to another issue I will close this issue.
