### ISSUE TITLE
Support for VS 2019 community edition

### ISSUE THREAD

**Issue by albert-t25** [NilsJPWerner/autoDocstring#80]
Does this support VS 2019 community edition? If not, is there some alternative? Thanks

**Comment by Modelmat** [comment]
This doesn't, this is for Visual Studio Code which is an entirely different product. You should be able to find something with a quick google.

**Comment by albert-t25** [comment]
I already searched in Google and didn't find something similar for Visual Studio. In any case thank you for the reply.

> This doesn't, this is for Visual Studio Code which is an entirely different product. You should be able to find something with a quick google.
