### ISSUE TITLE
Return hint with multiple values is not supported

### ISSUE THREAD

**Issue by ggtools** [NilsJPWerner/autoDocstring#81]
It looks like putting multiple value in the return hint breaks the template generation.

Let's start with a simple function and look at the generated doc (autoDocstring 0.3.0, Google style). The generated comments are close to perfection:
```python
def function_2(a, b: float, c=None) -> str:
    """[summary]
    
    Args:
        a ([type]): [description]
        b (float): [description]
        c ([type], optional): [description]. Defaults to None.
    
    Returns:
        str: [description]
    """
    pass
```

Now if I change the return value from `str` to `(str, float)` the code generation is now broken:
```python
def function_4(a, b: float, c=None) -> (str, float):
    """[summary]
    
    Args:
        float ([type]): [description]
    """
    pass
```

**Comment by NilsJPWerner** [comment]
Hi @ggtools, this is a case I hadn't anticipated at the time of creating the return parsing. I will add an improvement to support multiple return values.

**Comment by alkasm** [comment]
This issue should probably not break things anyways, but I don't believe `-> (str, float)` is a correct type annotation; AFAIK the correct return type should be `-> Tuple[str, float]` and autoDocstring works fine for this.

**Comment by NilsJPWerner** [comment]
After looking through some pep documents I believe @alkasm is correct.
