### ISSUE TITLE
No docstring generated on Remote-SSH

### ISSUE THREAD

**Issue by timsainb** [NilsJPWerner/autoDocstring#82]
auto docstring works fine locally, but on remote-ssh docstrings are not generated:

`command 'extension.generateDocstring' not found`

uninstalling and reinstalling did not work, nor did installing remotely.

**Comment by Larandar** [comment]
Yes because the extension is marked a needed on the remote side.

You can install it on the remote and it should work (it did on WSL).

**Comment by NilsJPWerner** [comment]
@timsainb did the advice from @Larandar help? If not I can setup a a remote environment to test things.

**Comment by timsainb** [comment]
@NilsJPWerner Thanks for following up. It doesn't seem to work for me. On the autoDocstring page, I get the message `Extension is enabled on `SSH myremoteservername``

**Comment by HaaLeo** [comment]
I think this issue can be prevented by explicitly setting the [`"extensionKind"`](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location)`: "workspace"` in the extensions `package.json`.

**Comment by NilsJPWerner** [comment]
I will add it to the package and we can see if the issues are fixed after the next release. I'm not currently setup to test this case so we will just have to see.

**Comment by NilsJPWerner** [comment]
@timsainb does this work over ssh now?

**Comment by timsainb** [comment]
Works great!
