### ISSUE TITLE
Update Name / Summary / Description of extension for discoverability

### ISSUE THREAD

**Issue by LightCC** [NilsJPWerner/autoDocstring#86]
It took me a while to find this extension. I limped along believing no one had made snippets for auto formatting docstrings for a good 2 months of using VS Code for Python. This is because this extension is not very discoverable using typical search terms in the VS Code extension search bar.

Putting in the following this extension currently ends up about 60-80 on my list of extensions that come up:
- "Python"
- "Python doc"
- "Python docstring"

It's not until I get close to the name of the extension with "python autodoc" that it even gets on the visible list of results (top 20), with completely non-Python extensions way ahead of it (Autodoc Yaml Snippets).

Just "docstring" it becomes 3 of only 5 extensions that show up, but if I put "docstring python" it drops way down again. I'm not sure where or what priority VS Code uses in parsing the search string relevance, but it appears the short description and lack of some key terms in the title of the extension is giving it limited visibility. I recommend changing the name of the extension to include Python, and possibly something like "Python Automatic Docstring Formatter (autoDocstring)", or at least update the description to have more key terms and see how that changes things, but the "Python" in the search term is definitely prioritizing anything with "Python" in the name ahead of this with many searches.

I already found it, (and great job, by the way) just trying to help others find it!

**Comment by NilsJPWerner** [comment]
Thank you for liking the extension. I appreciate the feedback on its discoverability. I will try and add some more keywords and possibly change the name to change "Python Docstrings".

**Comment by NilsJPWerner** [comment]
I have made some changes to the [package.json](https://github.com/NilsJPWerner/autoDocstring/blob/master/package.json) that hopefully will improve the extensions search rankings. I think I also want to improve the extension logo to incorporate the python colors and make it look a little more professional.

**Comment by meimchu** [comment]
Want to also just +1 to this as well :)

**Comment by NilsJPWerner** [comment]
Since I updated the keywords the extension is now consistently in the top 5 search results for the terms you suggested. Thank you for the suggestion! I still need to update the icon, but I think I can close this issue now.
