### ISSUE TITLE
Default docstring triggers 'W293 blank line contains whitespace'

### ISSUE THREAD

**Issue by mustyoshi** [NilsJPWerner/autoDocstring#90]
The default docstring seems to be triggering W293 for me.

**Comment by kd7vrc** [comment]
In my test, autoDocstring generates white space in blank lines which triggers the flake8 linter "blank line contains whitespace flake8(W293)" warning.  I believe blank lines should have no white space.

**Comment by NilsJPWerner** [comment]
This stems from the same issue as #34. Still waiting for vscode to fix their snippet issues. I will close this issue to consolidate messages in the other issue.
