### ISSUE TITLE
flake8: Missing blank line after last section

### ISSUE THREAD

**Issue by beeb** [NilsJPWerner/autoDocstring#92]
When linting docstrings generated with autoDocstring, flake8-docstrings complains that there is no blank line at the end of the docstring.

    Missing blank line after last section (D413)

Is this the desired behavior? Would there be an option to add a parameter in the settings to add a blank line before closing the triple quotes?

Cheers and thanks for a great extension!

**Comment by beeb** [comment]
I want to add that this only happens when the docstring has a "Returns" section. If only "Args" are present, no warning from flake8 appears.

**Comment by NilsJPWerner** [comment]
@beeb can you post an example of the warning? What docstring format are you using?

**Comment by beeb** [comment]
Sure thing @NilsJPWerner ! I'm using the `google` format.

<img width="665" alt="Screenshot 2019-12-18 at 07 48 17" src="https://user-images.githubusercontent.com/703631/71062482-e7f40380-216a-11ea-9763-8715b953b5ba.png">

**Comment by NilsJPWerner** [comment]
I just checked the flake8 [docs](https://readthedocs.org/projects/pydocstyle/downloads/pdf/latest/) and the December 9th update includes: 

```• Remove D413 from the google convention (#430).```

It looks like this error shouldn't apply to Google docstrings. Have you updated your flake8?

**Comment by beeb** [comment]
Hey good catch! I upgraded my pydocstyle to 5.0.x and the warning is gone. It seems this was a recent update, great!
