### ISSUE TITLE
How to remove the ‘square brackets’ for placeholders?

### ISSUE THREAD

**Issue by leon-work** [NilsJPWerner/autoDocstring#94]
Hi, there. I am wondering is there a way to remove the square brackets used in this extension?  

When I want to edit the comments like ''[Type]'' and  ''[description]'', it is a little annoying that I can not quick select the whole word with the brackets.  I know there is a hot key 'Tab', but it seems just works at the first time when I create the snippets. I'd like to remove the square brackets so that I can re-edit the strings.

**Comment by NilsJPWerner** [comment]
If I understand correctly, you are creating the docstring and then tabbing through without replacing the placeholders. Then when you come back to actually edit the [description] and [type] you double click the placeholder but it only selects the text?

You could try tabbing through the fields and deleting the placeholder values at first. I could also potentially add an option to change the placeholder text if this is common complaint.

**Comment by leon-work** [comment]
Yes. Sometimes I just create the docstring and then I have to inspect what is exactly the type or the array size is through the interactive window or elsewhere. When I come back to edit, if I double click the placeholder, I can just select the **type** and the brackets are not included in. It is frustrating I have to remove them manually. 

It will be great that there is an option to change the placeholder text. 

Thanks

**Comment by HitLuca** [comment]
+1 for this feature, but I cannot think of a delimiter that would both indicate that the particular docstring section has to be filled in and that can also be quickly selected altogether with a double click (`#test#`, `$test$`, `-test-` etc. all cannot be double clicked correctly)

**Comment by maxhoheiser** [comment]
+1

**Comment by chrissuda** [comment]
+1

**Comment by JOJ0** [comment]
+1 it's really really tedious. The tabbing doesn't work at all in my case (maybe clash with other extension, not sure), but anyway as has already beent pointed out: Usually after generation of a docstring not every type or description can be filled out by heart by tabbing through. The docstring has to be left to investigate and then coming back _always_ includes having to manually select (usually doubleclick) the type or description. And it gets pretty frustrating now.

My suggestion would be: Have the placeholders entirely disabled, making them regular words. Doubleclicking would be possible. Tabbing should then be disabled _at all_ 

To me personally this behaviour would speed up the process dramatically! Please consideer this and I hope it's technically possible!

Thanks a ton for a useful extension!

**Comment by JOJ0** [comment]
And also a question: Would a workaround be possible by editing the mustache.js template and remove the placeholders?

**Comment by LuchaoQi** [comment]
+1

**Comment by MHLut** [comment]
> And also a question: Would a workaround be possible by editing the mustache.js template and remove the placeholders there? If yes, where would I find the template?

You can do this:

1. Find the template you want to use as a base in `autoDocstring/tree/master/src/docstring/templates` and copy it to your local filesystem.
2. Remove every occurrence of `{{descriptionPlaceholder}}` from the template.
3. Place the custom template somewhere VSCode can access it and point setting `"autoDocstring.customTemplatePath"` to it.
