### ISSUE TITLE
[Google style] Multiline description should be indented

### ISSUE THREAD

**Issue by dumbPy** [NilsJPWerner/autoDocstring#98]
when overwriting the `[description]` section, if new line is inserted, it should by default be indented when using Google style, according to [sphinx documentation](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

**Comment by NilsJPWerner** [comment]
This can't be controlled by autoDocstring. By the time the docstring is inserted the extension has finished its work.

**Comment by dumbPy** [comment]
Makes sense. Thanks for the awesome extension !!!
